spring:
  application:
    name: account-service
  
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost:3306/trading_core?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        
  h2:
    console:
      enabled: true
      path: /h2-console

# Kafka Configuration
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: account-service-group
    auto-offset-reset: earliest
    enable-auto-commit: false
    isolation-level: read_committed
    max-poll-records: 100
    session-timeout-ms: 30000
  
  topics:
    order-events: order.events

server:
  port: 8083
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.trading.account: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG

saga:
  timeouts:
    order: 30
    matching: 10
    account: 5
  scheduler:
    check-interval: 2000