spring:
  application:
    name: cdc-module
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC

# CDC Configuration
cdc:
  database:
    hostname: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    name: ${DB_NAME:trading_core}  # 메인 애플리케이션 DB 이름
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}  # 메인 애플리케이션 비밀번호
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    order-events-topic: order.events
    schema-history-topic: dbhistory.order
  
  debezium:
    server-id: "184054"
    server-name: "order-service"
    offset-storage-file-name: "/tmp/offsets.dat"
    offset-flush-interval-ms: 1000
    poll-interval-ms: 100
    max-batch-size: 1024
    snapshot-mode: schema_only # schema_only, initial, never

# Logging Configuration
logging:
  level:
    root: INFO
    com.trading.cdc: DEBUG
    io.debezium: INFO
    org.apache.kafka: INFO
    org.springframework: INFO
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: logs/cdc-module.log
    max-size: 10MB
    max-history: 30

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Server Configuration
server:
  port: ${SERVER_PORT:8084}